#!/bin/sh
set -e
cat <<MSG
PANCANCER COMMAND LINE INTERFACE - INSTALLATION
-----------------------------------------------
This tool will setup a "launcher" host which has all of the tools we used to align and variant call
the PanCancer donors.  This launcher host can then launch one or more worker VMs with our Docker
workflows installed on them for processing one or more genomes specified by the user.

This system requires the following:
* Docker support in your Linux distribution (or boot2docker on a Mac)
* AWS credentials and/or OpenStack credentials
* A GNOS key (or keys) which are used to both download Docker images for our workflows, dependencies, as well as data from from GNOS servers used in the project
* Alternatively (or in addition to) the GNOS keys, a token for downloading workflows, dependencies, as well as donor data files from S3

DO YOU WISH TO CONTINUE [Y/N]:
MSG
read install_pancancer_launcher
#FYI: The weird "^^" is to make the user input into uppercase so that if they enter "y" the installer will still run.
if [ "${install_pancancer_launcher^^}" = 'Y' ] ; then
	sudo apt-get install wget
	echo "Installing docker..."
	wget -qO- https://get.docker.com/ | sh
	echo "Done!"
	echo "Pulling latest pancancer_launcher image..."
	docker pull pancancer/pancancer_launcher:latest
	echo "Done!"
else
	echo "You are exiting the installer now, but you can always run it again when you are ready."
fi

#TODO: download start_launcher_container.sh script...

#TODO: let user do their config stuff. Once configuration is finished, give them the option of starting up pancancer_launcher right away (they shouldn't have to call start_launcher_container.sh manually.)

echo "Exiting now."
set +e
